############# English navigation ##############

# main menu
# Removed Home and Contact from main menu since:
# - Logo click returns to home
# - Contact button available in header

# footer menu
[[footer]]
name = "Contact"
url = "/contact"
weight = 1


