baseURL = "http://neurality.solutions/"
languageCode = "en-us"
title = "Neurality Solutions"
theme = "hugo-fresh"

[params]
  description = "Biosignal interface for immersive interactions"
  contactEmail = "info@neurality.solutions"

