baseURL = "http://neurality.solutions/"
languageCode = "en-us"
title = "Neurality Solutions"
theme = "hugo-fresh"

[params]
  description = "Active Noise Cancellation for Human-Machine Interface"
  contactEmail = "info@neurality.solutions"

